"""Submission rules ERCOT states in prose that no XSD can express.

Each entry quotes ERCOT verbatim and names the page; a test checks every quote
against the vendored portal index.
"""

from __future__ import annotations

from dataclasses import dataclass

SILENT, PARTIAL, REJECT = "silent", "partial", "reject"
PORTAL = "https://developer.ercot.com/applications/ews"


@dataclass(frozen=True)
class Hazard:
    id: str
    severity: str  # silent: accepted but altered or ignored; partial: some of it stands
    what: str
    quote: str
    source: str
    guard: str
    checked: bool  # whether checker.check() tests a document for it


HAZARDS: tuple[Hazard, ...] = (
    Hazard(
        id="silent-hour-rounding",
        severity=SILENT,
        what="A time that should sit on an hour boundary may be moved to the nearest hour "
        "with no error.",
        quote="In cases where a time that is aligned with an hour boundary is expected, but "
        "not provided on a request message, the integration layer may round the time to the "
        "nearest hour. In this case, there may be no generation of an error message.",
        source=f"{PORTAL}/Services%20Organization/#representation-of-time",
        guard="Send startTime and endTime exactly on the hour.",
        checked=True,
    ),
    Hazard(
        id="silent-minute-rounding",
        severity=SILENT,
        what="A time off an interval boundary may be moved to the nearest minute, and an "
        "error may or may not follow.",
        quote="the integration layer may round the time to the nearest minute. This may "
        "result in an error being generated by the target application if the minute is not a "
        "valid interval boundary.",
        source=f"{PORTAL}/Services%20Organization/#representation-of-time",
        guard="Align times before sending; compare echoed times with the ones sent.",
        checked=False,
    ),
    Hazard(
        id="silent-combined-cycle-ignored",
        severity=SILENT,
        what="combinedCycle on a COP is accepted and discarded.",
        quote="Not required. Value ignored if provided.",
        source=f"{PORTAL}/Market%20Transaction%20Messages/Current%20Operating%20Plan%20%28COP%29/",
        guard="Do not rely on a field ERCOT documents as ignored.",
        checked=True,
    ),
    Hazard(
        id="silent-get-omits-rejected-bids",
        severity=SILENT,
        what="A get on a BidSet returns only accepted bids; a rejected bid is absent, not "
        "marked rejected.",
        quote="It will return all successful (accepted) bids and not the rejected bids.",
        source=f"{PORTAL}/Market%20Transaction%20Service/",
        guard="Reconcile returned mRIDs against those submitted; treat a missing one as "
        "rejected until a notification says otherwise.",
        checked=False,
    ),
    Hazard(
        id="silent-rrs-value1-ignored",
        severity=SILENT,
        what="On a Self-Arranged AS quantity with ASType RRS, TmPoint/value1 is ignored; the "
        "quantity comes from the three RRS subtype fields.",
        quote="When ASType of RRS is used, TmPoint/value1 is ignored, and the corresponding "
        "RRS subtype values are entered in the rrsuf_value, rrspf_value, and rrsff_value "
        "elements.",
        source=f"{PORTAL}/Market%20Transaction%20Messages/"
        "Self-Arranged%20Ancillary%20Service%20Quantities%20%28SAA%29/",
        guard="For RRS, fill rrsuf_value, rrspf_value and rrsff_value; leave value1 absent or 0.",
        checked=True,
    ),
    Hazard(
        id="partial-bidset-acceptance",
        severity=PARTIAL,
        what="A BidSet is accepted bid by bid: valid bids stand while invalid ones are rejected.",
        quote="For submissions containing multiple offers/bids, valid offers/bids are accepted "
        "as submitted, invalid offers/bids are rejected and marked with errors.",
        source=f"{PORTAL}/Market%20Transaction%20Service/#error-handling",
        guard="Reconcile the reply per transaction before treating the day as submitted.",
        checked=False,
    ),
    Hazard(
        id="partial-credit-rejection",
        severity=PARTIAL,
        what="A bid can be rejected for lack of credit approval, reported through the error "
        "notification rather than the synchronous reply.",
        quote="Error may also indicate the rejection of bids or offers for reasons such as the "
        "failure to receive credit approval.",
        source=f"{PORTAL}/Notifications%20Messages/Offer%20and%20Bid%20Set%20Errors/",
        guard="Treat the synchronous reply as receipt, not acceptance.",
        checked=False,
    ),
    Hazard(
        id="reject-one-bad-hour-voids-the-offer",
        severity=REJECT,
        what="One invalid hour rejects the whole offer or bid.",
        quote="An offer/bid will be rejected entirely if any hour within it is invalid.",
        source=f"{PORTAL}/Market%20Transaction%20Service/#error-handling",
        guard="Validate every hour before sending.",
        checked=False,
    ),
    Hazard(
        id="reject-overlapping-intervals",
        severity=REJECT,
        what="Intervals in a startTime/endTime sequence must not overlap, and are expected "
        "to meet end to start.",
        quote="overlapping time intervals are not allowed and will be flagged as an error. "
        "Typically in these cases the endTime for one interval should identically match the "
        "startTime for the next interval.",
        source=f"{PORTAL}/Services%20Organization/#representation-of-time",
        guard="Check that intervals tile: endTime[i] == startTime[i+1].",
        checked=True,
    ),
    Hazard(
        id="reject-overlapping-tpo-costs",
        severity=REJECT,
        what="Multiple StartupCost or MinimumEnergy entries in a ThreePartOffer must not "
        "overlap in time.",
        quote="if more than one StartupCost or MinimumEnergy is provided, there must not be "
        "overlapping start and end times",
        source=f"{PORTAL}/Market%20Transaction%20Messages/Three-Part%20Supply%20Offer%20%28TPO%29/",
        guard="Apply the tiling check per StartupCost and per MinimumEnergy group.",
        checked=True,
    ),
    Hazard(
        id="reject-hour-24",
        severity=REJECT,
        what="24:00 is excluded from the timestamps ERCOT accepts, although xs:dateTime allows it.",
        quote="Timestamps in messages sent to ERCOT by market participants could use any ISO "
        "8601 compliant timestamp (with the exception of 24:00, as described in section 1.6)",
        source=f"{PORTAL}/Services%20Organization/#representation-of-time",
        guard="Write hour ending 24 as 00:00 on the next day.",
        checked=True,
    ),
)

BY_ID = {h.id: h for h in HAZARDS}


def by_severity(severity: str) -> tuple[Hazard, ...]:
    return tuple(h for h in HAZARDS if h.severity == severity)
